## Importing Libraries and Data

#### Here, we will see a racing chart for the number of cured cases per state over time.

In [2]:
import math
import warnings
import numpy as np
import pandas as pd

In [3]:
cured = pd.read_csv('Cured_.csv',low_memory = False)

In [4]:
cured = cured.head(810)

In [5]:
cured

,Date,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,Dadra and Nagar Haveli and Daman and Diu,Delhi,Goa,...,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,Uttar Pradesh,Uttarakhand,West Bengal,Grand Total
0,03-2020,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,3.0
1,03-2020,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,0.0
2,03-2020,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,0.0,1.0,NaN,0.0,0.0,NaN,5.0,NaN,NaN,14.0
3,03-2020,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,0.0,-1.0,NaN,0.0,1.0,NaN,-1.0,NaN,NaN,0.0
4,03-2020,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,0.0,3.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,06-2022,46.0,1.0,20.0,92.0,64.0,95.0,3.0,1450.0,139.0,...,78.0,84.0,1.0,617.0,205.0,0.0,508.0,23.0,217.0,21834.0
806,06-2022,52.0,0.0,20.0,87.0,73.0,42.0,2.0,1665.0,78.0,...,89.0,125.0,1.0,691.0,285.0,0.0,525.0,1.0,212.0,30416.0
807,06-2022,34.0,0.0,10.0,52.0,45.0,64.0,1.0,1011.0,135.0,...,113.0,75.0,1.0,697.0,279.0,0.0,335.0,5.0,248.0,18972.0
808,06-2022,99.0,0.0,12.0,98.0,79.0,92.0,1.0,941.0,156.0,...,130.0,109.0,3.0,736.0,247.0,4.0,651.0,16.0,275.0,23148.0
809,06-2022,75.0,2.0,40.0,130.0,36.0,116.0,5.0,1265.0,151.0,...,125.0,105.0,2.0,764.0,236.0,0.0,635.0,29.0,296.0,27654.0

In [6]:
cured.fillna(0, inplace=True)

In [7]:
cured

,Date,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,Dadra and Nagar Haveli and Daman and Diu,Delhi,Goa,...,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,Uttar Pradesh,Uttarakhand,West Bengal,Grand Total
0,03-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
1,03-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,03-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,14.0
3,03-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,-1.0,0.0,0.0,1.0,0.0,-1.0,0.0,0.0,0.0
4,03-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,06-2022,46.0,1.0,20.0,92.0,64.0,95.0,3.0,1450.0,139.0,...,78.0,84.0,1.0,617.0,205.0,0.0,508.0,23.0,217.0,21834.0
806,06-2022,52.0,0.0,20.0,87.0,73.0,42.0,2.0,1665.0,78.0,...,89.0,125.0,1.0,691.0,285.0,0.0,525.0,1.0,212.0,30416.0
807,06-2022,34.0,0.0,10.0,52.0,45.0,64.0,1.0,1011.0,135.0,...,113.0,75.0,1.0,697.0,279.0,0.0,335.0,5.0,248.0,18972.0
808,06-2022,99.0,0.0,12.0,98.0,79.0,92.0,1.0,941.0,156.0,...,130.0,109.0,3.0,736.0,247.0,4.0,651.0,16.0,275.0,23148.0
809,06-2022,75.0,2.0,40.0,130.0,36.0,116.0,5.0,1265.0,151.0,...,125.0,105.0,2.0,764.0,236.0,0.0,635.0,29.0,296.0,27654.0

In [8]:
cured = cured.set_index('Date')

In [9]:
cured

,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,Dadra and Nagar Haveli and Daman and Diu,Delhi,Goa,Gujarat,...,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,Uttar Pradesh,Uttarakhand,West Bengal,Grand Total
Date,,,,,,,,,,,,,,,,,,,,,
03-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
03-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
03-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,14.0
03-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,-1.0,0.0,0.0,1.0,0.0,-1.0,0.0,0.0,0.0
03-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
06-2022,46.0,1.0,20.0,92.0,64.0,95.0,3.0,1450.0,139.0,218.0,...,78.0,84.0,1.0,617.0,205.0,0.0,508.0,23.0,217.0,21834.0
06-2022,52.0,0.0,20.0,87.0,73.0,42.0,2.0,1665.0,78.0,256.0,...,89.0,125.0,1.0,691.0,285.0,0.0,525.0,1.0,212.0,30416.0
06-2022,34.0,0.0,10.0,52.0,45.0,64.0,1.0,1011.0,135.0,248.0,...,113.0,75.0,1.0,697.0,279.0,0.0,335.0,5.0,248.0,18972.0
06-2022,99.0,0.0,12.0,98.0,79.0,92.0,1.0,941.0,156.0,248.0,...,130.0,109.0,3.0,736.0,247.0,4.0,651.0,16.0,275.0,23148.0
06-2022,75.0,2.0,40.0,130.0,36.0,116.0,5.0,1265.0,151.0,408.0,...,125.0,105.0,2.0,764.0,236.0,0.0,635.0,29.0,296.0,27654.0

In [10]:
cured.cumsum()

,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,Dadra and Nagar Haveli and Daman and Diu,Delhi,Goa,Gujarat,...,Punjab,Rajasthan,Sikkim,Tamil Nadu,Telangana,Tripura,Uttar Pradesh,Uttarakhand,West Bengal,Grand Total
Date,,,,,,,,,,,,,,,,,,,,,
03-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
03-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
03-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,17.0
03-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,4.0,0.0,0.0,17.0
03-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,3.0,0.0,0.0,1.0,0.0,4.0,0.0,0.0,23.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
06-2022,2305633.0,64216.0,716323.0,819021.0,91819.0,1138968.0,11447.0,1898541.0,243200.0,1216463.0,...,743446.0,1277411.0,38737.0,3422169.0,790897.0,99967.0,2060825.0,430129.0,1999767.0,85544793.0
06-2022,2305685.0,64216.0,716343.0,819108.0,91892.0,1139010.0,11449.0,1900206.0,243278.0,1216719.0,...,743535.0,1277536.0,38738.0,3422860.0,791182.0,99967.0,2061350.0,430130.0,1999979.0,85575209.0
06-2022,2305719.0,64216.0,716353.0,819160.0,91937.0,1139074.0,11450.0,1901217.0,243413.0,1216967.0,...,743648.0,1277611.0,38739.0,3423557.0,791461.0,99967.0,2061685.0,430135.0,2000227.0,85594181.0
06-2022,2305818.0,64216.0,716365.0,819258.0,92016.0,1139166.0,11451.0,1902158.0,243569.0,1217215.0,...,743778.0,1277720.0,38742.0,3424293.0,791708.0,99971.0,2062336.0,430151.0,2000502.0,85617329.0
06-2022,2305893.0,64218.0,716405.0,819388.0,92052.0,1139282.0,11456.0,1903423.0,243720.0,1217623.0,...,743903.0,1277825.0,38744.0,3425057.0,791944.0,99971.0,2062971.0,430180.0,2000798.0,85644983.0

In [11]:
cured = cured.astype(int)

In [12]:
cured = cured.cumsum()

In [17]:
cured.shape

(810, 35)

In [13]:
cured = cured.drop(['Grand Total'], axis=1)

In [14]:
import bar_chart_race as bcr

In [24]:
bcr.bar_chart_race(df = cured, period_length = 100, filename = 'Test2.mp4',cmap='dark12',bar_size = 0.3,sort='desc',
    n_bars=10,steps_per_period=20,
    period_summary_func=lambda v, r: {'x': .99, 'y': .18,
                                      's': f'Recovered: {v.nlargest(35).sum():,.0f}',
                                      'ha': 'right', 'size': 10, 'family': 'Courier New'},
    period_label={'x': .99, 'y': .1, 'ha': 'right', 'color': 'black'})

C:\Users\91861\anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:286: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_yticklabels(self.df_values.columns)
C:\Users\91861\anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:287: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels([max_val] * len(ax.get_xticks()))
C:\Users\91861\anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:226: UserWarning: Some of your columns never make an appearance in the animation. To reduce color repetition, set `filter_column_colors` to `True`
  warnings.warn("Some of your columns never make an appearance in the animation. "